/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <TempMes.h>

int main(void)
{

	__enable_irq();
	Init_Adc();
	Init_Timer();
	SCB->SCR|=2;
	__WFI();


	//GPIOA->BSRR|= GPIO_BSRR_BR_4;
	//read_Temp(d);


	//for(;;){

	//}
}
